### ISSUE TITLE
Getting error 299 when starting up

### ISSUE THREAD

**Issue by pakirambo** [WAZAAAAA0/TekkenBot#23] opened 2020-06-03 09:43 UTC
Started tekkenbot as admin, started tekken got the error.
![TekkenBotPrime_aXqoUaMiD4](https://user-images.githubusercontent.com/66361158/83621770-8c96c000-a5a8-11ea-8db1-24080c20795d.png)

**Comment by compsyguy** [comment] 2020-06-04 06:07
That's typical with the current build, it should go away when you get into a match. Right now its such a minor thing, its more effort to fix it then its worth.

**Comment by WAZAAAAA0** [comment] 2021-03-24 11:26
duplicate of https://github.com/WAZAAAAA0/TekkenBot/issues/19

**Closed by WAZAAAAA0** 2021-03-24 11:26 UTC
