### ISSUE TITLE
Bot doesn't work with 4.20 patch.

### ISSUE THREAD

**Issue by zeratul7x** [WAZAAAAA0/TekkenBot#34] opened 2021-03-26 19:31 UTC
Latest release TekkenBotPrime_v0.20.0 doesn't work with 4.20 patch.
Error message:
```
Found TekkenGame-Win64-Shipping.exe
ReadProcessMemory Error: Code 299
Tekken pid acquired: 1928
Trying to acquire Tekken library in pid: 1928
```

**Comment by WAZAAAAA0** [comment] 2021-03-26 22:58
duplicate of https://github.com/WAZAAAAA0/TekkenBot/issues/23, just ignore the error and enter training mode, it still works

**Closed by WAZAAAAA0** 2021-03-26 22:58 UTC
