### ISSUE TITLE
Throwbreak not working?

### ISSUE THREAD

**Issue by rajnmaker** [WAZAAAAA0/TekkenBot#38] opened 2021-05-02 16:46 UTC
TekkenEncyclopedia.py
finally run the bot normally from GUI_TekkenBotPrime.py. Your character should now automatically press the corresponding keyboard button to break throws

I changed it like this and launched GUI_TekkenBotPrime.py but nothing's working

**Comment by WAZAAAAA0** [comment] 2023-05-06 09:43
duplicate of https://github.com/WAZAAAAA0/TekkenBot/issues/32, can't reproduce, likely outdated by now (reopen the older issue if necessary)

**Closed** 2023-05-06 09:43 UTC
